# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yaroslav/OOP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yaroslav/OOP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaroslav/OOP/CMakeFiles /home/yaroslav/OOP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaroslav/OOP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game.out

# Build rule for target.
game.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game.out
.PHONY : game.out

# fast build rule for target.
game.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/build
.PHONY : game.out/fast

Characteristic/Armor.o: Characteristic/Armor.cpp.o
.PHONY : Characteristic/Armor.o

# target to build an object file
Characteristic/Armor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Armor.cpp.o
.PHONY : Characteristic/Armor.cpp.o

Characteristic/Armor.i: Characteristic/Armor.cpp.i
.PHONY : Characteristic/Armor.i

# target to preprocess a source file
Characteristic/Armor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Armor.cpp.i
.PHONY : Characteristic/Armor.cpp.i

Characteristic/Armor.s: Characteristic/Armor.cpp.s
.PHONY : Characteristic/Armor.s

# target to generate assembly for a file
Characteristic/Armor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Armor.cpp.s
.PHONY : Characteristic/Armor.cpp.s

Characteristic/Characteristic.o: Characteristic/Characteristic.cpp.o
.PHONY : Characteristic/Characteristic.o

# target to build an object file
Characteristic/Characteristic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Characteristic.cpp.o
.PHONY : Characteristic/Characteristic.cpp.o

Characteristic/Characteristic.i: Characteristic/Characteristic.cpp.i
.PHONY : Characteristic/Characteristic.i

# target to preprocess a source file
Characteristic/Characteristic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Characteristic.cpp.i
.PHONY : Characteristic/Characteristic.cpp.i

Characteristic/Characteristic.s: Characteristic/Characteristic.cpp.s
.PHONY : Characteristic/Characteristic.s

# target to generate assembly for a file
Characteristic/Characteristic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Characteristic.cpp.s
.PHONY : Characteristic/Characteristic.cpp.s

Characteristic/Count.o: Characteristic/Count.cpp.o
.PHONY : Characteristic/Count.o

# target to build an object file
Characteristic/Count.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Count.cpp.o
.PHONY : Characteristic/Count.cpp.o

Characteristic/Count.i: Characteristic/Count.cpp.i
.PHONY : Characteristic/Count.i

# target to preprocess a source file
Characteristic/Count.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Count.cpp.i
.PHONY : Characteristic/Count.cpp.i

Characteristic/Count.s: Characteristic/Count.cpp.s
.PHONY : Characteristic/Count.s

# target to generate assembly for a file
Characteristic/Count.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Count.cpp.s
.PHONY : Characteristic/Count.cpp.s

Characteristic/Health.o: Characteristic/Health.cpp.o
.PHONY : Characteristic/Health.o

# target to build an object file
Characteristic/Health.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Health.cpp.o
.PHONY : Characteristic/Health.cpp.o

Characteristic/Health.i: Characteristic/Health.cpp.i
.PHONY : Characteristic/Health.i

# target to preprocess a source file
Characteristic/Health.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Health.cpp.i
.PHONY : Characteristic/Health.cpp.i

Characteristic/Health.s: Characteristic/Health.cpp.s
.PHONY : Characteristic/Health.s

# target to generate assembly for a file
Characteristic/Health.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Health.cpp.s
.PHONY : Characteristic/Health.cpp.s

Characteristic/Money.o: Characteristic/Money.cpp.o
.PHONY : Characteristic/Money.o

# target to build an object file
Characteristic/Money.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Money.cpp.o
.PHONY : Characteristic/Money.cpp.o

Characteristic/Money.i: Characteristic/Money.cpp.i
.PHONY : Characteristic/Money.i

# target to preprocess a source file
Characteristic/Money.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Money.cpp.i
.PHONY : Characteristic/Money.cpp.i

Characteristic/Money.s: Characteristic/Money.cpp.s
.PHONY : Characteristic/Money.s

# target to generate assembly for a file
Characteristic/Money.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Money.cpp.s
.PHONY : Characteristic/Money.cpp.s

Characteristic/Power.o: Characteristic/Power.cpp.o
.PHONY : Characteristic/Power.o

# target to build an object file
Characteristic/Power.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Power.cpp.o
.PHONY : Characteristic/Power.cpp.o

Characteristic/Power.i: Characteristic/Power.cpp.i
.PHONY : Characteristic/Power.i

# target to preprocess a source file
Characteristic/Power.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Power.cpp.i
.PHONY : Characteristic/Power.cpp.i

Characteristic/Power.s: Characteristic/Power.cpp.s
.PHONY : Characteristic/Power.s

# target to generate assembly for a file
Characteristic/Power.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Power.cpp.s
.PHONY : Characteristic/Power.cpp.s

Characteristic/Score.o: Characteristic/Score.cpp.o
.PHONY : Characteristic/Score.o

# target to build an object file
Characteristic/Score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Score.cpp.o
.PHONY : Characteristic/Score.cpp.o

Characteristic/Score.i: Characteristic/Score.cpp.i
.PHONY : Characteristic/Score.i

# target to preprocess a source file
Characteristic/Score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Score.cpp.i
.PHONY : Characteristic/Score.cpp.i

Characteristic/Score.s: Characteristic/Score.cpp.s
.PHONY : Characteristic/Score.s

# target to generate assembly for a file
Characteristic/Score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Score.cpp.s
.PHONY : Characteristic/Score.cpp.s

Field/Field.o: Field/Field.cpp.o
.PHONY : Field/Field.o

# target to build an object file
Field/Field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.cpp.o
.PHONY : Field/Field.cpp.o

Field/Field.i: Field/Field.cpp.i
.PHONY : Field/Field.i

# target to preprocess a source file
Field/Field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.cpp.i
.PHONY : Field/Field.cpp.i

Field/Field.s: Field/Field.cpp.s
.PHONY : Field/Field.s

# target to generate assembly for a file
Field/Field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.cpp.s
.PHONY : Field/Field.cpp.s

Field/Square.o: Field/Square.cpp.o
.PHONY : Field/Square.o

# target to build an object file
Field/Square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Square.cpp.o
.PHONY : Field/Square.cpp.o

Field/Square.i: Field/Square.cpp.i
.PHONY : Field/Square.i

# target to preprocess a source file
Field/Square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Square.cpp.i
.PHONY : Field/Square.cpp.i

Field/Square.s: Field/Square.cpp.s
.PHONY : Field/Square.s

# target to generate assembly for a file
Field/Square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Square.cpp.s
.PHONY : Field/Square.cpp.s

Item/Item.o: Item/Item.cpp.o
.PHONY : Item/Item.o

# target to build an object file
Item/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Item.cpp.o
.PHONY : Item/Item.cpp.o

Item/Item.i: Item/Item.cpp.i
.PHONY : Item/Item.i

# target to preprocess a source file
Item/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Item.cpp.i
.PHONY : Item/Item.cpp.i

Item/Item.s: Item/Item.cpp.s
.PHONY : Item/Item.s

# target to generate assembly for a file
Item/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Item.cpp.s
.PHONY : Item/Item.cpp.s

Item/Weapon.o: Item/Weapon.cpp.o
.PHONY : Item/Weapon.o

# target to build an object file
Item/Weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Weapon.cpp.o
.PHONY : Item/Weapon.cpp.o

Item/Weapon.i: Item/Weapon.cpp.i
.PHONY : Item/Weapon.i

# target to preprocess a source file
Item/Weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Weapon.cpp.i
.PHONY : Item/Weapon.cpp.i

Item/Weapon.s: Item/Weapon.cpp.s
.PHONY : Item/Weapon.s

# target to generate assembly for a file
Item/Weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Weapon.cpp.s
.PHONY : Item/Weapon.cpp.s

Move/Coordinate.o: Move/Coordinate.cpp.o
.PHONY : Move/Coordinate.o

# target to build an object file
Move/Coordinate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Coordinate.cpp.o
.PHONY : Move/Coordinate.cpp.o

Move/Coordinate.i: Move/Coordinate.cpp.i
.PHONY : Move/Coordinate.i

# target to preprocess a source file
Move/Coordinate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Coordinate.cpp.i
.PHONY : Move/Coordinate.cpp.i

Move/Coordinate.s: Move/Coordinate.cpp.s
.PHONY : Move/Coordinate.s

# target to generate assembly for a file
Move/Coordinate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Coordinate.cpp.s
.PHONY : Move/Coordinate.cpp.s

Move/Direction.o: Move/Direction.cpp.o
.PHONY : Move/Direction.o

# target to build an object file
Move/Direction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Direction.cpp.o
.PHONY : Move/Direction.cpp.o

Move/Direction.i: Move/Direction.cpp.i
.PHONY : Move/Direction.i

# target to preprocess a source file
Move/Direction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Direction.cpp.i
.PHONY : Move/Direction.cpp.i

Move/Direction.s: Move/Direction.cpp.s
.PHONY : Move/Direction.s

# target to generate assembly for a file
Move/Direction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Direction.cpp.s
.PHONY : Move/Direction.cpp.s

Move/MoveManager.o: Move/MoveManager.cpp.o
.PHONY : Move/MoveManager.o

# target to build an object file
Move/MoveManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/MoveManager.cpp.o
.PHONY : Move/MoveManager.cpp.o

Move/MoveManager.i: Move/MoveManager.cpp.i
.PHONY : Move/MoveManager.i

# target to preprocess a source file
Move/MoveManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/MoveManager.cpp.i
.PHONY : Move/MoveManager.cpp.i

Move/MoveManager.s: Move/MoveManager.cpp.s
.PHONY : Move/MoveManager.s

# target to generate assembly for a file
Move/MoveManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/MoveManager.cpp.s
.PHONY : Move/MoveManager.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.cpp.s
.PHONY : Player.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game.out"
	@echo "... Characteristic/Armor.o"
	@echo "... Characteristic/Armor.i"
	@echo "... Characteristic/Armor.s"
	@echo "... Characteristic/Characteristic.o"
	@echo "... Characteristic/Characteristic.i"
	@echo "... Characteristic/Characteristic.s"
	@echo "... Characteristic/Count.o"
	@echo "... Characteristic/Count.i"
	@echo "... Characteristic/Count.s"
	@echo "... Characteristic/Health.o"
	@echo "... Characteristic/Health.i"
	@echo "... Characteristic/Health.s"
	@echo "... Characteristic/Money.o"
	@echo "... Characteristic/Money.i"
	@echo "... Characteristic/Money.s"
	@echo "... Characteristic/Power.o"
	@echo "... Characteristic/Power.i"
	@echo "... Characteristic/Power.s"
	@echo "... Characteristic/Score.o"
	@echo "... Characteristic/Score.i"
	@echo "... Characteristic/Score.s"
	@echo "... Field/Field.o"
	@echo "... Field/Field.i"
	@echo "... Field/Field.s"
	@echo "... Field/Square.o"
	@echo "... Field/Square.i"
	@echo "... Field/Square.s"
	@echo "... Item/Item.o"
	@echo "... Item/Item.i"
	@echo "... Item/Item.s"
	@echo "... Item/Weapon.o"
	@echo "... Item/Weapon.i"
	@echo "... Item/Weapon.s"
	@echo "... Move/Coordinate.o"
	@echo "... Move/Coordinate.i"
	@echo "... Move/Coordinate.s"
	@echo "... Move/Direction.o"
	@echo "... Move/Direction.i"
	@echo "... Move/Direction.s"
	@echo "... Move/MoveManager.o"
	@echo "... Move/MoveManager.i"
	@echo "... Move/MoveManager.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

