# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yaroslav/OOP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yaroslav/OOP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaroslav/OOP/CMakeFiles /home/yaroslav/OOP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaroslav/OOP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game.out

# Build rule for target.
game.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game.out
.PHONY : game.out

# fast build rule for target.
game.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/build
.PHONY : game.out/fast

# target to build an object file
Characteristic/Armor.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Armor.o
.PHONY : Characteristic/Armor.o

# target to preprocess a source file
Characteristic/Armor.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Armor.i
.PHONY : Characteristic/Armor.i

# target to generate assembly for a file
Characteristic/Armor.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Armor.s
.PHONY : Characteristic/Armor.s

# target to build an object file
Characteristic/Characteristic.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Characteristic.o
.PHONY : Characteristic/Characteristic.o

# target to preprocess a source file
Characteristic/Characteristic.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Characteristic.i
.PHONY : Characteristic/Characteristic.i

# target to generate assembly for a file
Characteristic/Characteristic.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Characteristic.s
.PHONY : Characteristic/Characteristic.s

# target to build an object file
Characteristic/Count.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Count.o
.PHONY : Characteristic/Count.o

# target to preprocess a source file
Characteristic/Count.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Count.i
.PHONY : Characteristic/Count.i

# target to generate assembly for a file
Characteristic/Count.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Count.s
.PHONY : Characteristic/Count.s

# target to build an object file
Characteristic/Health.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Health.o
.PHONY : Characteristic/Health.o

# target to preprocess a source file
Characteristic/Health.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Health.i
.PHONY : Characteristic/Health.i

# target to generate assembly for a file
Characteristic/Health.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Health.s
.PHONY : Characteristic/Health.s

# target to build an object file
Characteristic/Money.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Money.o
.PHONY : Characteristic/Money.o

# target to preprocess a source file
Characteristic/Money.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Money.i
.PHONY : Characteristic/Money.i

# target to generate assembly for a file
Characteristic/Money.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Money.s
.PHONY : Characteristic/Money.s

# target to build an object file
Characteristic/Power.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Power.o
.PHONY : Characteristic/Power.o

# target to preprocess a source file
Characteristic/Power.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Power.i
.PHONY : Characteristic/Power.i

# target to generate assembly for a file
Characteristic/Power.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Power.s
.PHONY : Characteristic/Power.s

# target to build an object file
Characteristic/Score.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Score.o
.PHONY : Characteristic/Score.o

# target to preprocess a source file
Characteristic/Score.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Score.i
.PHONY : Characteristic/Score.i

# target to generate assembly for a file
Characteristic/Score.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Characteristic/Score.s
.PHONY : Characteristic/Score.s

# target to build an object file
EventManager/Event/NoneEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/NoneEvent.o
.PHONY : EventManager/Event/NoneEvent.o

# target to preprocess a source file
EventManager/Event/NoneEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/NoneEvent.i
.PHONY : EventManager/Event/NoneEvent.i

# target to generate assembly for a file
EventManager/Event/NoneEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/NoneEvent.s
.PHONY : EventManager/Event/NoneEvent.s

# target to build an object file
EventManager/Event/TeleportEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TeleportEvent.o
.PHONY : EventManager/Event/TeleportEvent.o

# target to preprocess a source file
EventManager/Event/TeleportEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TeleportEvent.i
.PHONY : EventManager/Event/TeleportEvent.i

# target to generate assembly for a file
EventManager/Event/TeleportEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TeleportEvent.s
.PHONY : EventManager/Event/TeleportEvent.s

# target to build an object file
EventManager/Event/TrapEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TrapEvent.o
.PHONY : EventManager/Event/TrapEvent.o

# target to preprocess a source file
EventManager/Event/TrapEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TrapEvent.i
.PHONY : EventManager/Event/TrapEvent.i

# target to generate assembly for a file
EventManager/Event/TrapEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TrapEvent.s
.PHONY : EventManager/Event/TrapEvent.s

# target to build an object file
EventManager/Event/TreatEvent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TreatEvent.o
.PHONY : EventManager/Event/TreatEvent.o

# target to preprocess a source file
EventManager/Event/TreatEvent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TreatEvent.i
.PHONY : EventManager/Event/TreatEvent.i

# target to generate assembly for a file
EventManager/Event/TreatEvent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/Event/TreatEvent.s
.PHONY : EventManager/Event/TreatEvent.s

# target to build an object file
EventManager/EventManager.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/EventManager.o
.PHONY : EventManager/EventManager.o

# target to preprocess a source file
EventManager/EventManager.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/EventManager.i
.PHONY : EventManager/EventManager.i

# target to generate assembly for a file
EventManager/EventManager.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/EventManager/EventManager.s
.PHONY : EventManager/EventManager.s

# target to build an object file
Field/Field.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.o
.PHONY : Field/Field.o

# target to preprocess a source file
Field/Field.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.i
.PHONY : Field/Field.i

# target to generate assembly for a file
Field/Field.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Field.s
.PHONY : Field/Field.s

# target to build an object file
Field/FieldCreator.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/FieldCreator.o
.PHONY : Field/FieldCreator.o

# target to preprocess a source file
Field/FieldCreator.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/FieldCreator.i
.PHONY : Field/FieldCreator.i

# target to generate assembly for a file
Field/FieldCreator.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/FieldCreator.s
.PHONY : Field/FieldCreator.s

# target to build an object file
Field/Square.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Square.o
.PHONY : Field/Square.o

# target to preprocess a source file
Field/Square.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Square.i
.PHONY : Field/Square.i

# target to generate assembly for a file
Field/Square.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Field/Square.s
.PHONY : Field/Square.s

# target to build an object file
Game/GameManager.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Game/GameManager.o
.PHONY : Game/GameManager.o

# target to preprocess a source file
Game/GameManager.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Game/GameManager.i
.PHONY : Game/GameManager.i

# target to generate assembly for a file
Game/GameManager.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Game/GameManager.s
.PHONY : Game/GameManager.s

# target to build an object file
Input/Input.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Input/Input.o
.PHONY : Input/Input.o

# target to preprocess a source file
Input/Input.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Input/Input.i
.PHONY : Input/Input.i

# target to generate assembly for a file
Input/Input.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Input/Input.s
.PHONY : Input/Input.s

# target to build an object file
Item/Item.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Item.o
.PHONY : Item/Item.o

# target to preprocess a source file
Item/Item.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Item.i
.PHONY : Item/Item.i

# target to generate assembly for a file
Item/Item.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Item.s
.PHONY : Item/Item.s

# target to build an object file
Item/Weapon.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Weapon.o
.PHONY : Item/Weapon.o

# target to preprocess a source file
Item/Weapon.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Weapon.i
.PHONY : Item/Weapon.i

# target to generate assembly for a file
Item/Weapon.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Item/Weapon.s
.PHONY : Item/Weapon.s

# target to build an object file
Move/Coordinate.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Coordinate.o
.PHONY : Move/Coordinate.o

# target to preprocess a source file
Move/Coordinate.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Coordinate.i
.PHONY : Move/Coordinate.i

# target to generate assembly for a file
Move/Coordinate.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Coordinate.s
.PHONY : Move/Coordinate.s

# target to build an object file
Move/Direction.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Direction.o
.PHONY : Move/Direction.o

# target to preprocess a source file
Move/Direction.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Direction.i
.PHONY : Move/Direction.i

# target to generate assembly for a file
Move/Direction.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/Direction.s
.PHONY : Move/Direction.s

# target to build an object file
Move/MoveManager.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/MoveManager.o
.PHONY : Move/MoveManager.o

# target to preprocess a source file
Move/MoveManager.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/MoveManager.i
.PHONY : Move/MoveManager.i

# target to generate assembly for a file
Move/MoveManager.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Move/MoveManager.s
.PHONY : Move/MoveManager.s

# target to build an object file
Player.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.o
.PHONY : Player.o

# target to preprocess a source file
Player.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.i
.PHONY : Player.i

# target to generate assembly for a file
Player.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/Player.s
.PHONY : Player.s

# target to build an object file
main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.out.dir/build.make CMakeFiles/game.out.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game.out"
	@echo "... Characteristic/Armor.o"
	@echo "... Characteristic/Armor.i"
	@echo "... Characteristic/Armor.s"
	@echo "... Characteristic/Characteristic.o"
	@echo "... Characteristic/Characteristic.i"
	@echo "... Characteristic/Characteristic.s"
	@echo "... Characteristic/Count.o"
	@echo "... Characteristic/Count.i"
	@echo "... Characteristic/Count.s"
	@echo "... Characteristic/Health.o"
	@echo "... Characteristic/Health.i"
	@echo "... Characteristic/Health.s"
	@echo "... Characteristic/Money.o"
	@echo "... Characteristic/Money.i"
	@echo "... Characteristic/Money.s"
	@echo "... Characteristic/Power.o"
	@echo "... Characteristic/Power.i"
	@echo "... Characteristic/Power.s"
	@echo "... Characteristic/Score.o"
	@echo "... Characteristic/Score.i"
	@echo "... Characteristic/Score.s"
	@echo "... EventManager/Event/NoneEvent.o"
	@echo "... EventManager/Event/NoneEvent.i"
	@echo "... EventManager/Event/NoneEvent.s"
	@echo "... EventManager/Event/TeleportEvent.o"
	@echo "... EventManager/Event/TeleportEvent.i"
	@echo "... EventManager/Event/TeleportEvent.s"
	@echo "... EventManager/Event/TrapEvent.o"
	@echo "... EventManager/Event/TrapEvent.i"
	@echo "... EventManager/Event/TrapEvent.s"
	@echo "... EventManager/Event/TreatEvent.o"
	@echo "... EventManager/Event/TreatEvent.i"
	@echo "... EventManager/Event/TreatEvent.s"
	@echo "... EventManager/EventManager.o"
	@echo "... EventManager/EventManager.i"
	@echo "... EventManager/EventManager.s"
	@echo "... Field/Field.o"
	@echo "... Field/Field.i"
	@echo "... Field/Field.s"
	@echo "... Field/FieldCreator.o"
	@echo "... Field/FieldCreator.i"
	@echo "... Field/FieldCreator.s"
	@echo "... Field/Square.o"
	@echo "... Field/Square.i"
	@echo "... Field/Square.s"
	@echo "... Game/GameManager.o"
	@echo "... Game/GameManager.i"
	@echo "... Game/GameManager.s"
	@echo "... Input/Input.o"
	@echo "... Input/Input.i"
	@echo "... Input/Input.s"
	@echo "... Item/Item.o"
	@echo "... Item/Item.i"
	@echo "... Item/Item.s"
	@echo "... Item/Weapon.o"
	@echo "... Item/Weapon.i"
	@echo "... Item/Weapon.s"
	@echo "... Move/Coordinate.o"
	@echo "... Move/Coordinate.i"
	@echo "... Move/Coordinate.s"
	@echo "... Move/Direction.o"
	@echo "... Move/Direction.i"
	@echo "... Move/Direction.s"
	@echo "... Move/MoveManager.o"
	@echo "... Move/MoveManager.i"
	@echo "... Move/MoveManager.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

